version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/deploy
    overwrite: true
hooks:
  AfterInstall:
    - location: scripts/install_composer_dependencies.sh
      timeout: 300
      runas: root
